demo:
  outputs:
    dev:
      dbname: demo_db
      host: postgres
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASS') }}"
      port: 5432
      schema: demo
      threads: 1
      type: postgres

  target: dev
