services:
  postgres:
    build: ./postgres
    image: dbt-demo/postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dbt-demo

  dbt-demo-seed:
    build: ./dbt/demo
    image: dbt-demo/demo
    platform: linux/amd64
    command: ["seed"]
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/dbt.env
    networks:
      - dbt-demo
    depends_on:
      - postgres

  dbt-demo:
    image: dbt-demo/demo
    platform: linux/amd64
    command: ["run"]
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/dbt.env
    networks:
      - dbt-demo
    depends_on:
      - dbt-demo-seed

  dbt-demo-test:
    image: dbt-demo/demo
    platform: linux/amd64
    command: ["test"]
    env_file:
      - ./env/dbt.env
    networks:
      - dbt-demo
    depends_on:
      - dbt-demo

  dbt-demo-docs:
    image: dbt-demo/demo
    platform: linux/amd64
    entrypoint: ["/entrypoint_docs.sh"]
    env_file:
      - ./env/dbt.env
    ports:
      - "8080:8080"
    networks:
      - dbt-demo
    depends_on:
      - postgres

networks:
  dbt-demo:
    name: dbt-demo

volumes:
  postgres:
