services:
  postgres:
    build: ./postgres
    image: dbt-demo/postgres
    deploy:
      restart_policy:
        condition: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dbt-demo

  dbt-demo:
    build: ./dbt/demo
    image: dbt-demo/demo
    platform: linux/amd64
    command: ["run"]
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - dbt-demo
    depends_on:
      - postgres

networks:
  dbt-demo:
    name: dbt-demo

volumes:
  postgres:
